name: Pruebas Unitarias Modulares

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # Apuntamos a la carpeta 'Pruebas1'
    
    - name: 1. Ejecutar Pruebas de Calculadora (Financiero)
      run: python Pruebas1/test_calculadora.py

    - name: 2. Ejecutar Pruebas de Validador (Estados)
      run: python Pruebas1/test_validador.py
